name: sklearn-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - azure-ai-ml==1.12.0
    - mlflow==2.9.2
    - scikit-learn==1.3.2
    - pandas==2.1.4
    - numpy==1.24.3
